### ISSUE TITLE
Decide on one order of document types for the Kyma components

### ISSUE THREAD

**Issue by kazydek** [kyma-project/community#148]
**Description**

Decide what should be the order of document types that should be used consistently in all component docs under [`kyma/docs`](https://github.com/kyma-project/kyma/tree/master/docs).
- Propose the order by updating the list of obligatory docs in [`content-strategy.md`](https://github.com/kyma-project/community/blob/master/guidelines/content-guidelines/content-strategy.md#obligatory) accordingly. Consult the choice with other TWs (it can be done through comments in the pull request).
- Add a note to the document explaining that the order is binding and should be used for all components. 
- Rename `Getting Started` type of docs into `Tutorial`, as agreed on the SIG Content.

**Reasons**

Consistency in docs

**Comment by kazydek** [comment]
And what about other obligatory types?

**Comment by bszwarc** [comment]
I had a look at what we have among the docs and found the following: 
- Overview
- Architecture
- Details
- CR
- CLI
- Configuration
+ some without any particular type, like `istio-patch.md` but these probably can be turned into `details` 🤔

**Comment by klaudiagrz** [comment]
+ Getting Started Guides

If we stay with the `Overview -> Architecture -> Details` order for the beginning, I'd say that the next in line should be `CRs` together with the overview document enlisting all the resources used by the particular component, then `GSGs`. 

I have no clue where to put `CLI reference` type of docs. It mentions the general terms and basic operations so it looks strange at the very end, but also does not fit at the beginning. Because of this doc type, one may have an impression that the content is doubled when reading the component's documentation (as for the SC documentation: we mention resources in the details, then at the end of documentation in the CLI reference). Maybe it should be before the details then? Or right after the details? Any ideas?

**Comment by klaudiagrz** [comment]
As agreed on the SIG Content, this is the proper order of the document types:
1. Overview
2. Architecture
3. Details
4. Installation (if applicable)
5. Configuration (if applicable)
6. CR
7. CLI
8. Getting Started renamed into Tutorial
9. other types
