### ISSUE TITLE
Customized GitHub analytics

### ISSUE THREAD

**Issue by anajankovic** [kyma-project/community#33]
Hi,

We need customized GitHub analytics for the Kyma project.
These analytics should include the following KPIs:
 
- No of external contributors
- No of external downloads/clones
- No of external issues (bugs, improvements, comments, reviews, PRs…)
- Commits per external contributor 

These data should be filtered by period. Analytics should have a summary dashboard covering main KPIs listed above in the form of numbers. Also, we need a detail view of each KPI in a form of numbers and graphs. 

A reference for the GitHub analytics is the Google analytics. 

I hope this was detailed enough for you to work on a script. Let me know if you need more input from my side.  
 
Best,
Ana

**Comment by derberg** [comment]
What do you mean by `A reference for the GitHub analytics is the Google analytics.`

I guess you want it in a kind of combined view from all repositories and not single view for repo like this https://github.com/kyma-project/kyma/graphs/traffic ?

I'm not sure if all of this can be achieved by GitHub API, like for example `No of external downloads/clones`. We need to validate available functionality first

**Comment by derberg** [comment]
Also, I understand that gitential is not enough, and even if we enable https://www.openhub.net/p/gardener like gardener it also will not be sufficient, right? the biggest requirement is the overview of contributors that are not members of kyma-project organization?

**Comment by anajankovic** [comment]
That is right. The two main requirements is to know how many external contributors and how many external issues/bugs/improvements we have.

**Comment by derberg** [comment]
How do you want to get this data? how you want to access them? Web page? report? Real time or on demand?

**Comment by anajankovic** [comment]
Real time in the form of the web page. So, that i can also share the link with the management and they can also see data any time.

**Comment by derberg** [comment]
because these are publicly available data I guess that form of the webpage could land here for example kyma-project.io/stats ?

**Comment by derberg** [comment]
**Long Term**
after initial research, gitential and openhub assesment, understanding how getting [historical data](https://www.gharchive.org/) out from github is complicated I don't see any other tool than https://github.com/cncf/devstats really hosted as grafana https://k8s.devstats.cncf.io/ 
Why historical data? for example one contributor can be now a member of one company and then the other one, so results might be different depending on the date.

**Short Term**
Doable but challenging. Latest API version for GraphQL doesn't support getting contributors info. The old REST API does but getting proper data in place is a bit more complicated. 

The most tricky part is how to define an external contributor. I assume it is a person that is not a member of Kyma organization, but long term it is tricky assumption because what if the contributor gets invited into organization, do we treat him as external or internal contributor? I assume that for now on such an early stage we understand "external" as a person is not an SAP employee as we want to measure how the project gets adopted outside the company that donated Kyma to the open source. But even here it is getting tricky, SAP has huge number of developers, do we all treat them as internal contributors?

We need some further discussion before we jump into implementation as deeper I analyze the topic, more complicated it gets. Maybe short term it is really just a simple script that prints some data and long term really a web page

**Comment by derberg** [comment]
We agree for now on short term solution:
- Web site is not a must
- External contributor is a person that is not kyma-project member
- Long term topic is parked for now
- clones/dowloads KPI is not a must have

**Comment by anajankovic** [comment]
👍

**Comment by derberg** [comment]
this is WIP

**Comment by derberg** [comment]
still valid

**Comment by anajankovic** [comment]
@derberg Is this still valid?

**Comment by derberg** [comment]
definitely, I will not extend the app I created but we still need stats

**Comment by anajankovic** [comment]
still valid
