### ISSUE TITLE
Don't release Kyma components with charts

### ISSUE THREAD

**Issue by sjanota** [kyma-project/community#339]
Created on 2019-08-08 by Szymon Janota (@sjanota).

## Decision log

| Name | Description |
|-----------------------|------------------------------------------------------------------------------------|
| Title | Don't release Kyma components with charts |
| Due date | `2019-08-16` |
| Status | Proposed on `2019-08-08` |
| Decision type | Binary |
| Affected decisions | None |

## Context

The current release process involves building all images of Kyma components. It is because images in charts may not be actual and not reflected in source code. Because of that, all images need to be built and bumped again before release. As a result, all integration tests must pass on release and all code owners must approve release PR.  This makes a release very long and unpleasant experience.

## Decision
The decision is to abandon the requirement that source code and charts must be synchronized. With that in mind, the new release process is described below.

### Start Release
To start a new release branch Release Master creates a branch `release-x.y` from the master branch. 

### Create new version
To create a new version from this branch
1. Release Master creates a PR with an update to the `KYMA_VERSION` file in Kyma repository. For example, the first PR should change it to `x.y.z-rc1`.
2. The release branch is protected with a guard job that fails if any PR image is present on the release branch. If any team uses PR images they need to change them on the PR before release version can be published.
3. When a PR with changes in this file is merged a post-submit job is triggered. The job builds a new Installer image with the given version and publishes release artifacts to GitHub.
Every kind of release follows the same process: RC, major, minor and patch. 

### Kyma patches
When the need for a patch arises Release Master creates a PR to release branch with version changed. Component images that need patching are modified on this branch. 

### Component patches
When patch in a component is required contributor must:
1. Create additional branch in Kyma repository: `release-x.y-{component-name}`
2. Create a PR with a patch to the component. When PR is merged post-submit job publishes the new image. 
3. Update the image in release charts following the process above. 
Optionally, image from master may be used if component wasn't changed in the meantime.

### Generic job
All of the components will use the same generic job template. The job will expect `make release` target to exists and provide docker. Makefile may use docker to access any required tools and other dependencies need to release the artifact. Also, there will be the same job for master and previous releases using the same template. Whenever the template needs to be changed new job will be created instead and the old will be preserved. This job should change rarely, thus there will be a lot fewer jobs. Makefiles will be simplified because every pre and post submit will use same target.

### Use templates to generate jobs
Jobs for components will be generated using templates. Release master needs to add release to the configuration file, regenerate the template and commit changed jobs.

## Consequences
* Source code and charts on release branch are not in sync.
* Additional branches in Kyma repository for patched components
* Burden of making integration tests pass on the release branch is put on teams
* Code dependencies are versioned with code.
* Fewer jobs to create. 
* Simpler makefiles
* kyma-project/kyma#2595 implemented by the way
* Easier creation of new jobs.

**Comment by pkosiec** [comment]
In this approach, if we will omit integration tests while creating release branch, we will still need to run integration tests for any other version than RC1. I think it doesn’t make sense to resign from them, as this is a one-time benefit only and we won't be exactly sure what we are releasing. How we can say that some commit in `master` is stable? The situation, when all tests are green on master is not a usual one 😄 And we cannot pick commits where at least one test is red. What if this is not false-negative?

**Comment by pkosiec** [comment]
Let's assume that:
- we still want to run integration tests on every release
- we still want to use "one PR" approach, which means using `PR-XXX` images on `master branch`

To run integration tests, we need to open a pull request to release branch (as they run as presubmit jobs). To open a pull request, we need to do a change.  We could still replace images tags from `values.yaml` files.

So the basic idea would be to still use `PR-XXX` values in charts on `master`, but during a release they could be replaced with commit hashes - because the images are built as postsubmit jobs.

During a release, we could replace `values.yaml` automatically with some script on the release pull request. The script would look for `PR-XXX` image tags, and it will replace them with hashes of commit, where the change occurred. How? By constructing image path `eu.gcr.io/kyma-project/component-name:PR-XXX` path and getting all tags for a given image and picking the commit hash tag. The post-master jobs would tag PR images, not rebuild them as it is right now.

The script could be run manually by Release Master when it's time to do a release.

Getting approvals from all teams on release PR is time-consuming. To ensure we don’t have to get teams approval, we can set owners to all `values.yaml` files to `developers` team.

In a result, we can open release PR in maximum one minute. On every release we will run integration tests, we will have image tags with git commit hashes, without rebuilding all components and any other team involved.

**Advantages**
- Faster release because:
  - we don’t prepare release jobs for components for every release
  - we don’t get approvals from all teams
  - we don’t modify any `values.yaml` files manually during the release (as it is in your original proposal)
- We keep "one PR" approach
- Also, we still keep release validation because of integration tests.

**Disadvantages**
- multiple branches for component patches (this is the disadvantage of your original proposal, but it will be resolved while splitting `kyma` components to multiple repos)
- owners lose control over `values.yaml` files inside charts

**Comment by aszecowka** [comment]
Let me add my 2 cents ;)

> The current release process involves building all images of Kyma components. 

For release 1.4, all component jobs started at 	16:23, the most time-consuming job is  console-backend-service - 14 minutes

> It is because images in charts may not be actual and not reflected in source code. Because of that, all images need to be built and bumped again before release. 

If bumping to release version will be automatic, this time is negligible. What takes time is reviewing and accepting such PR by all teams. I see value in that because every time needs to ensure that proper image is used for all their components. 

> As a result, all integration tests must pass on the release and all code owners must approve release PR. This makes a release very long and unpleasant experience.

Running integration tests is a must IMO. You may say "but they were executed for master branch". Yes, but what about patches? We haven't tested Kyma with such a set of images. If you want to have a different approach for the first release (RC-1), and for others, it makes release process not consistent.

> Source code and charts on release branch are not in sync

So troubleshooting can become a nightmare. Let assume that I have a problem with the cooperation of two Kyma components, then I have to checkout Kyma twice in different places to see actual source code of my components.

> Additional branches in Kyma repository

Now, if you want to fix a problem with a given component, you need to create pr to the release branch. In your approach, I have an additional step, to create a branch for a specific component in a specific version. What about external contributors who want to provide a fix for a released component? Are they allowed to create such a branch? If not, how such a process will look like?
In addition to that, if you want to fix 2 components for a given release, you have to create 2 branches.

> Release Master needs to make a decision where to create a release branch. This is more important than before because the rc1 cluster will be created from that point without additional integration tests.

How do you want to ensure that Release Master created a release branch from a good commit? Right now you see on the PR that all required jobs passed (including integration tests).

Another consequence, which is not mentioned here is forbidding committing code and bumping components image in the same version.
Some facts: I analyzed the last 300 PR to kyma, in 242 of them changes were made to the test or components code, 52 contains changes for code and charts in the same PR. 
Consequences of this proposal are the following: developers have to create 20% more PR to achieve the same state as with "one-pr approach". 


If you want to rerun my test, here is a very simple source code:
```
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)
/**
query {
    repository(name:"kyma",owner:"kyma-project") {
        pullRequests(first: 100,orderBy: {field: CREATED_AT, direction: DESC}) {
            pageInfo {
                endCursor
                hasNextPage
            }
			nodes{
                title
                number
                files(first: 100) {
                    edges {
                        node {
                            path
                        }
                    }
                    totalCount

                }

}
        }
    }
}
 */
func main() {
	both := 0
	any := 0
	hasMoreFiles := 0
	files := []string{"1.json", "2.json", "3.json"} // I fetched 3 pages of data
	for _, f := range files {
		f, err := os.Open(fmt.Sprintf("<path to the files>%s", f))
		if err != nil {
			panic(err)
		}

		d := json.NewDecoder(f)
		r := Response{}
		if err := d.Decode(&r); err != nil {
			panic(err)
		}

		for _, pr := range r.Data.Repository.PullRequests.Nodes {
			componentsModified := false
			resourcesModified := false
			testsModified := false


			if len(pr.Files.Edges) >= 100 {
				hasMoreFiles++
			}

			for _, f := range pr.Files.Edges {

				if strings.HasPrefix(f.Node.Path, "components/") {
					componentsModified = true
				}
				if strings.HasPrefix(f.Node.Path, "tests/") {
					testsModified = true
				}
				if strings.HasPrefix(f.Node.Path, "resources/") {
					resourcesModified = true
				}
				if componentsModified && resourcesModified {
					break
				}
			}

			if (componentsModified || testsModified) && resourcesModified {
				fmt.Println(pr.Number)
				both++
			}
			if componentsModified || resourcesModified || testsModified {
				any++
			}
		}
	}
	fmt.Printf("%d/%d/%d\n", both, any, 300-hasMoreFiles)

}

type Response struct {
	Data struct {
		Repository struct {
			PullRequests struct {
				PageInfo struct {
					EndCursor   string `json:"endCursor"`
					HasNextPage bool   `json:"hasNextPage"`
				} `json:"pageInfo"`
				Nodes []struct {
					Title  string `json:"title"`
					Number int    `json:"number"`
					Files  struct {
						Edges []struct {
							Node struct {
								Path string `json:"path"`
							} `json:"node"`
						} `json:"edges"`
						TotalCount int `json:"totalCount"`
					} `json:"files"`
				} `json:"nodes"`
			} `json:"pullRequests"`
		} `json:"repository"`
	} `json:"data"`
}

```

To not only criticize, there are also some parts that I really like in this proposal. 
If we get rid of creating release jobs for every release it will be really helpful. As I know from Krystain Cieslik, you plan to change buildpack image that is used in the test-infra; it will contain only docker and make and other dependencies will be kept in kyma repository, next to the components code.
In addition to that, I would vote for still using release versions for components, but automate changing values.yaml. I am a fan of building the most up-to-date images because then we have a clear state in the repository that reflects images used in the charts.
Not bumping images should be considered as bad practice - we can introduce a job that reports which components are outdated.

**Comment by sjanota** [comment]
@pkosiec @aszecowka I'm not a fan of bot committing to Kyma repository. How about we go the most simplistic way:

1. Add a simple job on release branch that checks `grep PR-* -r resources | wc -l == 0` )not exactly, but you know what I mean). If any image is PR-XXX it fails and the appropriate team needs to bump the image. 
2. We remove all release jobs for components.
3. The patch is a fully manual process. You may either take the image from the master branch or create the patched image any other way. If it includes defining prow job the person doing patch needs to create one.

Other than that everything works like it was until now.

**Comment by pkosiec** [comment]
> I'm not a fan of bot committing to Kyma repository

I didn't say anything about bot. Please read my counter-proposal carefully:

> The script could be run manually by Release Master when it's time to do a release.

It would result in a commit with Release Master as the original author, and it would be done only on release branch.

> Add a simple job on release branch that checks grep PR-* -r resources | wc -l == 0 )not exactly, but you know what I mean).

Still you need to prepare the job that run script, which looks for all PR-XXX occurences. So if we have them all, why can't we replace them with proper hash tags?

The way you described still doesn't enable one PR approach. And how would you like to create a new release? Why does it matter to not change values.yaml, if you still need to do any change to create a pull request to release branch?
