### ISSUE TITLE
Define Kyma main punch line - Elevator Pitch

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/community#460]
We need a short 1-2 paragraphs long sentence regarding what is Kyma and what problems it solves.

- We could use the [Open Canvas](https://docs.google.com/presentation/d/1f2ljO9enLKaN7tfmvj1v9ADbLKqFgjVqkoqaDS91Ga8/edit#slide=id.gef3740a7b_1_12) format suggested by [mozillascience](http://mozillascience.github.io/working-open-workshop/)

**Comment by valentinvieriu** [comment]
Here is a proposal from my side. Please take it as a draft

> Being a Cloud Native Developer can be a quite hard. Kubernetes should simplify things, but instead introduced a complete new layer of complexity that can be intimidating for developers that just want to care about building their apps.
We created Kyma to be there for the Cloud Native Developer, hold their hand and offer them a batteries included Cloud-Native Application Runtime to let them focus on what they do best, build apps.

**Comment by pbochynski** [comment]
I had such sentence in one of my presentations:

> Kyma gives you a properly configured, monitored, and secured Kubernetes cluster. It combines various open-source projects for authentication, logging, eventing, alerting, tracing, and many more. We ensured they play well together so you can only focus on coding.

Just a few bullet points that we should also consider:
- set of opinionated tools that are essential for building and running microservices or serverless functions
- security by design (service mesh with mutual TLS, predefined roles for administrator and developers sharing k8s cluster,  integrated Micro API Gateway and OAuth2 server)
- easy consumption of services by providing OSBA Brokers (for Microsoft, Google, AWS and SAP)

**Comment by mszostok** [comment]
_my two cents_
I totally agree with PB but regarding the bullet points that were mentioned, I just want to highlight one thing. As you said Kyma connects and configure different components from **HUGE** [CNCF landscape](https://landscape.cncf.io/) and by doing so end-user can easily start with k8s by focusing on implementing business logic as we give them all batteries included.

But one thing which is also important in my opinion is that you are not always able to connect those project together because you will end-up with some gaps between them so Kyma also takes care of filling that gaps by implementing own components/solution e.g. Rafter, Helm-Broker, CBS etc. so as a result user a nice look and feel as we do not only install and configure already present projects abut also filling the gaps which provide a more smooth and easily uses of those projects together.

**Comment by majakurcius** [comment]
Taking into account all the input provided above, I came up with the following: 

> Kyma is a Cloud Native Application Runtime that gives you the power of Kubernetes but without the hassle of worrying about security, configuration and integration of tools. Kyma does it for you, as it not only combines various components needed for Cloud Native development, but also fills the gaps between them to make them work smoothly together and let you focus on your work. All you need to do is install and set up Kyma and you’re good to go, with a ready-to-use cluster, and a Console UI, too!
The batteries-included approach ensures easier building and running of microservices and serverless functions and easier service consumption, as we handpick the essential tools from the huge CNCF landscape, glue them together adding whatever’s needed to make them play smoothly with each other, ensure security, top it off with a UI, and wrap in up nicely for you as Kyma so you can jump straight to developing applications.

This is a draft version and feedback and comments are most welcome :)

**Comment by evilyeti** [comment]
Folks, 
I miss the **extend** part from the _Extend your applications with Kubernetes_ slogan. 
And imho - this is what puts Kyma apart from the other application runtime environments out there, all running on Kubernetes. Talking about _application development_, while staying completely abstract on the application technology (Java, Python, node.js, etc) falls a bit short, compared to other environments, where service consumption, libraries and events are wired natively in the respective language constructs. 
This might be a missing rubber layer between Kyma and applications/microservices on top, but without it - I believe we can't achieve the differentiation we've always strived for over the course of the last 2 years - to make service consumption as easy as possible, thus providing a unique environment for cloud native developers to interact with the world of enterprise software and cloud services. 

My 2 cents.
