### ISSUE TITLE
Proposal for WG installation

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/community#464]
**Proposal type**

* Working Group (WG)

**Name**
* Full name of the group: working group installation

* Abbreviated name: wg-installation

**Earliest start date**

* 2020-06-01

**Visibility**
* Public

**Keywords** (optional)

* installation
* helm

**Proposers**

* @piotrmsc 

**Purpose and goals**

Installation is an important, large and extensive topic in kyma, it consists not only of the kyma-installer itself as the component but also of topics such as the integration with Cloud Providers (GCP,AWS,Azure,Gardener), kyma-cli, infrastructure (prow),  installation profiles (lite, standard, production), charts and last but not least the documentation. I would like to drive installation domain together with anyone that is interested and keen on working on such a topic.

The group's goal is to discuss, develop, implement or adopt best practices and solutions that will streamline and improve the quality of kyma installation.

Here are examples of functional goals we would like to achieve within this WG: 

- decrease installation time
- redefine and provide new kyma lite profile
- provide an easy way to install/uninstall additional, optional components at runtime
- parallel installation of components  (address dependency management)
- allow easy and quick local development 

**Benefits**

Having an open working group will allow everyone from our kyma organization as well as from our community to be involved in installation topics. Share feedback and work directly on the given topic in the form of POC or, if accepted, target implementation. Additionally, this will make kyma more transparent to the community (from installation roadmap point of view for example) and might be a good open source community practice, perhaps increasing our visibility in the open source world.

**Expected results**

**Expected membership and governance**

* Meeting frequency: weekly
* Membership: 8
* Duration: 6 months

**Previous approach** (optional)

We've been implementing and driving this domain internally, mostly by a single team.

**Measures of success** 

* Covered by POC defined technical strategy for the future of kyma installation ( kyma-operator vs helm-operator vs non-helm operator vs pure yamls vs sth else)
* Installation has reduced time
* Dynamic component loading with parallel option
* Fast local development (the underlying hosting solution has quick boot time, allows easy interaction without modifying any of the hosts files whenever possible)

**Assessment frequency**

* Monthly

**Exit criteria**

* Members will be inactive or interest will significantly drop down making it very hard to drive and implement topics
* All the goals will be met/completed
* Global product priorities will change

**Comment by a-thaler** [comment]
I welcome that initiative, we need to invest in that area and pro-actively involving interested people is a really good idea. So I will approve that proposal, but still want to bring in two topics upfront to be considered potentially in the description.

From my experience with trying to write a helm chart for kyma, I would like to see the focus much more in the application lifecycle direction aka having a full-fletched kyma-operator in place rather than an installer. Following the basic idea of an operator (and not having that notion of a programmatic installation process) will help us in many areas of usability and expectation management.
I don't want to imply here any technical direction. How the operator is working under the hood should be the outcome of the group. But if we plan to have some software in this area (which is not the case if we go with pure yaml file, fine), then it should follow the operator pattern and be named like that.
With that I prefer to get rid of the "installer" term at all, there is only the kyma-operator taking care of reaching the configured setup, no matter if it is a fresh install or a config change. If you agree, let's even name the working group in that direction like "wg-kyma-operator"

Furthermore, I like to see outlined a bit more the requirements from the two different personas which I see, at the moment the proposal addresses some problems it wants to fix but it is not describing the targeted look & feel of the MVP. Of course you can analyse this as part of the group activity, anyway I like to write down my view as inspiration

As a Kyma Admin:
- I can setup kyma with my custom component list and individual component configuration with one operation (no need to wait in between required like "first install basic kyma and wait, then add an optional component") - I can verify when the setup is finished with success or get good error indicators
- I can change the configuration of a specific component - I see that the change gets processed and see if the change got applied with success - The change will not affect other components in any way
- I can provide configuration in full yaml syntax in case of a helm based solution
- I can request to remove a component or full kyma - I can see the status of the removal
- I can upgrade to a newer version (either by component or centrally) and see the status

As a Kyma component maintainer:
- I have global context/config available in my component telling me the used cloud provider, the kyma version, the K8S version, the domain,... so that I can change the component setup accordingly, think of monitoring setup on different cloud providers.
- In order to test my component I can point the kyma configuration to custom online sources (no need to build an installer image)
- there is a well-defined way of providing custom upgrade logic

**Comment by pbochynski** [comment]
I approve of the initiative. And thanks @a-thaler for the requirements - I think we should start the discussion in the group with them.

**Comment by pbochynski** [comment]
As the majority of the steering committee already accepted, please proceed.

**Comment by piotrmsc** [comment]
@a-thaler I would not name it wg-kyma-operator as it would indicate a component, installation is a domain/area it is not related to single component like I mentioned in the description. However, I agree that in terms of component naming, kyma-operator is better than kyma-installer.

**Comment by a-thaler** [comment]
fair point :)
