### ISSUE TITLE
Check documentation against insensitive terms (master/slave, whitelist/blacklist)

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/community#515]
**Description**

SAP customers and employees questioned the use of “insensitive language” in the software industry, especially
- blacklist / whitelist
- master / slave

SAP is therefore [replacing these terms with an inclusive language](https://blogs.wdf.sap.corp/sapnews_en/2020/09/replacing-insensitive-terms-to-make-the-software-industry-more-inclusive/) that helps to create a more inclusive workplace and ecosystem. To comply with this vision, we must check our documentation and correct the usage of `blacklist`/`whitelist` terms. Two other insensitive terms (`master`/`slave`) will be corrected after GitHub changes them in their infrastructure.

**Reasons**

SAP is replacing these terms with an inclusive language that helps to create a more inclusive workplace and ecosystem.

**Assignees**

@kyma-project/technical-writers

**Comment by technical-writers** [comment]
Hi @klaudiagrz 👋 This is not the technical-writers user you're looking for. Please remove it and tag the user who will be picking up this issue 👍

**Comment by kazydek** [comment]
The Nighbours team renamed `master` branches to `main` in the following repositories:

- `kyma-project` organization:
  - [`busola`](https://github.com/kyma-project/busola)
  - [`busola-migrator`](https://github.com/kyma-project/busola-migrator)
  - [`cli`](https://github.com/kyma-project/cli)
  - [`community`](https://github.com/kyma-project/community)
  - [`control-plane`](https://github.com/kyma-project/control-plane)
  - [`examples`](https://github.com/kyma-project/examples)
  - [`hydroform`](https://github.com/kyma-project/hydroform) (moved from `kyma-incubator`)
  - [`kyma`](https://github.com/kyma-project/kyma)
  - [`test-infra`](https://github.com/kyma-project/test-infra)
  - [`third-party-images`](https://github.com/kyma-project/third-party-images) (moved from `kyma-incubator`)
  - [`website`](https://github.com/kyma-project/website)

- `kyma-incubator` organization:
  - [`api-gateway`](https://github.com/kyma-incubator/api-gateway)
  - [`documentation-component`](https://github.com/kyma-incubator/documentation-component)
  - [`metris`](https://github.com/kyma-incubator/metris)

Where applicable, they modified `ci-master` to `ci-main`, and Prow job names to include `main` instead of `master`.
TWs adjusted MD files to include these changes as well and replaced, wherever possible, all insensitive terms with their inclusive alternatives.

**Comment by kazydek** [comment]
Latest update:

- **Docs:** Doc-related changes are finished. There was one PR logged as a [follow-up issue](https://github.com/kyma-project/kyma/issues/11109) logged with the Goats team to change insensitive terms in the API Gateway component in the `kyma` and `api-gateway` repository (mostly code, but there are also mentions of the insensitive terms in the [README.md](https://github.com/kyma-incubator/api-gateway/blob/main/README.md). It also needs to be modified once the code terms are corrected.)

- **Infrastructure:** [Prowjobs](https://github.com/kyma-project/test-infra/issues/3381) are renamed to `pre/post-main`, branches of not deprecated repos were renamed to `main`.
Waiting for the [last PR](https://github.com/kyma-project/test-infra/pull/3613) for renaming Presets to be merged.

**Comment by kazydek** [comment]
Closing the issue as [PR 3613](https://github.com/kyma-project/test-infra/pull/3613) has already been merged.
