### ISSUE TITLE
Reduce workload for technical writers

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/community#611]
**Description**

Technical writers are required to review all pull requests that contain changes in markdown files. As their input is very valuable it also creates a big load of tasks that are not so important as external documentation. 
The idea is to remove `*.md` line below:

https://github.com/kyma-project/kyma/blob/96d7d7e23470c34882f9f1c10fb7312c5e0665c1/CODEOWNERS#L272-L276

You can still ask for the review for internal documentation (not published on the website), but it should not block your PR.

**Comment by pbochynski** [comment]
README.md in the root folder should be also reviewed by TW.

**Comment by pbochynski** [comment]
Note: remember it is not only about TW. It is also about other contributors/code-owners who want to speed up the process. It is a case where you can judge on your own that the change doesn't require the TW review. Even though such reviews are rather quick and do not block PR for a longer period the problem was reported.

We can also extend the discussion to cover the review process in general. Right now it is based on hunting people on slack. Maybe we can experiment with [auto-assignment](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#configuring-auto-assignment) or come with another solution that generates less noise and reduces "time to merge".

**Comment by valentinvieriu** [comment]
I think this will speed up our PR approval process, we find ourselves quite open in the situation of waiting for approval from TW even if it's just a merge conflict.
I support this proposal.

**Comment by Disper** [comment]
@valentinvieriu could you link few PRs where the waiting time for approval was longer than expected? Some data could be helpful in understanding the situation more.

**Comment by janmedrek** [comment]
@pbochynski I fully agree it is **also** about improving the review process. For language one we could think about introducing two "types" of review - for internal and external documentation, this would simplify the process and both sides would know what to expect from each of them (internal docu review would not be as extensive, or will be skipped in some cases at all).

Regarding the approval issues - as you've said there is a hunt going on with every review, not just the docu ones, so I am all-in on a general improvement, we should work towards having a faster review process **without** losing the quality. 

Also - since our sources are "open" we can say that all documentation is user-facing, that's why I am worried dropping language review at all will lead to some sort of degradation of quality, I am not strongly opposing the proposal though, just wanted to share some concerns regarding this change, would love to hear more opinions on this.

**Comment by pbochynski** [comment]
I created another ticket to propose review assignment automation: https://github.com/kyma-project/community/issues/613
We can move discussion there.

**Comment by klaudiagrz** [comment]
@pbochynski Should we close this issue then?
