### ISSUE TITLE
Frequently Asked Questions about Prow work flow

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/community#658]
I would like to address this issue as place for some frequently asked question about Prow work and review flow.

Recently several of the repositories, kyma, test-infra, cli, third-party-images and compass, have the new flow enabled, effectively removing the write access to the developers to these repositories. This created some concerns and questions wether the change was right or not. There were some key points this flow had to tackle:

* We wanted to resolve problems with excessive permissions for everyone to the project
* We want to secure the upstream repositories in case of potential security data breaches
* We aim to increase the automation level in the long-term with efficient tooling
* We want to provide the functionality where the GitHub notifications will be actually useful for the developers in their daily flow
* We aim to reduce the number of message noise in Slack to minimum
* We want to extend the GitHub's basic role-based access control with more advanced integrations which are not, and probably won't be available at the time being
* We wanted to provide easy way for the teams to maintain their ownerships across repository directories

This flow of course killed some of the features that most of you found convenient for now:

* Using task lists in the Issue description
* Assigning people to the issue from the GitHub UI
* Adding issues to the project from the issue page (@k15r proposed an automation and we will most likely adapt that for entire Kyma)

The list of those inconveniences probably is longer than that. Those are really valid points and I know some of you may see it as a regression in the daily workflow. Unfortunately those 3 subjects are tightly related to the write permission to the repository, which is out of question overly permissive, when given to everyone. We acknowledged those problems and will be actively working on a solution to provide you at least some automation for the problems you reported.

Another part of the topic is that I would like to gather the feedback in this issue about everything related to the Prow flow. I will then gather everything in convenient FAQ section in the community documentation with proper examples on how you can resolve some problems you experience with the bot commands and other tricks. The 3 problems listed above will be included in that FAQ by default.

It's a collaborative work so let's spend at least 5 minutes of your work time to look at this issue.

**Comment by jakobmoellersap** [comment]
Thank you for the detailed summary of all the points. First of All: I think the current approach works, and it will do its job. So no urgent change necessary. However if all devs are unhappy with the workflow we should change some aspects of our approach.

My current Standpoint:

> We wanted to resolve problems with excessive permissions for everyone to the project

What is defined as excessive in our case? I would really like to see documented who is proposing these permissions as too excessive and for whom it is a compliance problem. I will totally live with that if there is some higher order or some requirement standard we would fulfil (and that we couldn't in the standard), but most of the time the developers working on the repository are the ones who have access to managing the repository. I would argue that most people think the roles proposed in the [Github Documentation for Organizations](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization) as well as [Github Documentation on Roles](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization) are enough to fulfil our requirements if nothing explicitly is specified otherwise.

> We want to secure the upstream repositories in case of potential security data breaches

I would argue a security breach can be tackled by using established security features in github, e.g. through [Enforcing 2FA](https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-two-factor-authentication-for-your-organization/requiring-two-factor-authentication-in-your-organization). I think by explaining what explicitly cannot be solved with this in the FAQ we would answer that question prematurely.

> We aim to increase the automation level in the long-term with efficient tooling

While I totally see this, with Github Actions and Prow we already have powerful tooling in place that we could extend on-demand without relaying on this system. We would need to answer with concrete examples on what is now better possible than it was before with Github API etc.

>We want to provide the functionality where the GitHub notifications will be actually useful for the developers in their daily flow

If you currently are subscribed to an issue / PR and enable notifications on comments, this will be inflated by the commands. Maybe there is something here that I don't see but I cannot imagine that this adds anything to the GitHub notifications. What I see is that it mostly duplicates the assignments of labels (as you see right above in this message) and this will trigger separate notifications because the Github API takes this as 2 Actions. We should explain in the FAQ what exactly can be improved in the notification workflow.

>We aim to reduce the number of message noise in Slack to minimum

I do not see how this has increased since the new workflow. It would be great to explain the improvements concretely in the FAQ.

>We want to extend the GitHub's basic role-based access control with more advanced integrations which are not, and probably won't be available at the time being

What do we want to use this RBAC extensions for? I thought the Code-Owners files as well as separate repositories for different concerns are well established methods. Could you share in the FAQ what kind of other extensions we plan to integrate with?

**Comment by Disper** [comment]
I've captured an issue with potential improvements that would help with user experience for anyone using GitHub Projects (Beta) - https://github.com/kyma-project/test-infra/issues/5294. I believe that all the points that are not yet improved, should be at least answered in the FAQ.

**Comment by PK85** [comment]
@Ressetkk is it already done? If not consider reopening.

**Comment by Ressetkk** [comment]
@PK85 since we backed away from Prow flow, there is no point in reopening it for now.
